Repository kalviumcommunity/S76_Vigneshwaran_Capstone_WildNect, pull requests merged in 2025-05, with the labels that each got.

#8 get species in root
  server/Routes/Species.js
  server/index.js
Labels: Review effort 2/5

#10 gemini model switch
  server/Routes/Species.js
Labels: Review effort 1/5

#12 add signup
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/assets/images/butterfly.gif
  client/src/assets/images/nature.gif
  client/src/pages/Signup.jsx
  client/src/routes/Routes.js
Labels: Review effort 2/5

#13 fix backend deploy link
  README.md
Labels: Review effort 1/5

#14 Implemented Authentication
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/assets/images/Google__G__logo.svg.webp
  client/src/components/GoogleAuthButton.jsx
  client/src/components/SpeciesForm.jsx
  client/src/firebase.js
  client/src/pages/Dashboard.jsx
  client/src/pages/Login.jsx
  client/src/pages/SignIn.jsx
  client/src/pages/Signup.jsx
  client/src/routes/Routes.js
  server/Routes/Auth.js
  server/index.js
  server/models/BadgeSchema.js
  server/models/ChatSchema.js
  server/models/CommentSchema.js
  server/models/LeaderSchema.js
  server/models/SpeciesSchema.js
  server/models/UserSchema.js
  server/package-lock.json
  server/package.json
Labels: Review effort 3/5

#15 using jwt
  client/src/pages/Login.jsx
  client/src/pages/Signup.jsx
  server/Routes/Auth.js
  server/index.js
  server/middleware/verifyToken.js
  server/package-lock.json
  server/package.json
Labels: Review effort 3/5
